name: Publish Packages

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12.22.1
          registry-url: https://npm.pkg.github.com/
          always-auth: true
      - run: yarn
      - run: |
          cd packages/package-a
          yarn publish --registry https://npm.pkg.github.com/ --force --new-version 1.0.1
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}