name: Publish Packages

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12.22.1
      - run: yarn
      - name: Install npm-cli-login tool
        run: npm install --global npm-cli-login
      - name: Publish CT extensions
        run: |
          WORKDIR="packages"
          TOKEN_CMD="npm-cli-login -u c0d3t0g3th3r -p cm132n4123j4kbnnbdcas -e info@codetogether.com -r https://npm.codetogether.io -s @codetogether"
          BUILD_NUMBER=${{ github.run_number }}
          cd "$WORKDIR"
          $TOKEN_CMD
          for d in */ ; do
            echo "Working on $d"
            ( cd "$d" &&
              PUB_VERSION="2023.2.${BUILD_NUMBER}" &&
              echo "Publish package version is: $PUB_VERSION" &&
              yarn publish --registry https://npm.codetogether.io --force --no-git-tag-version --new-version $PUB_VERSION )
          done